[package]
name = "http-webhookd"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[dependencies]
env_logger = "0.8.2"
hyper = "0.13.9"
log = "0.4.11"
serde = { version = "1.0.118", features = ["derive"] }
structopt = "0.3.21"
tokio = { version = "0.2.24", features = ["rt-core", "process", "stream", "io-util"] }
toml = "0.5.7"
